### PR TITLE
Set interface IP

### PR DESCRIPTION
**Pull request by systemcrash**
New PR which corresponds to the older, closed #6

### CODE REVIEW

**Comment by systemcrash** [comment]
I think this PR is ready. Testers welcome.

**Comment by LewdNeko** [comment]
```py
Traceback (most recent call last):
  File "E:\Projects\Web Dev\airplay2-receiver-flags\ap2-receiver.py", line 740, in <module>
    if ifen[ni.AF_INET6]:
KeyError: 23
```

This on my device which doesn't support IPv4.

**Comment by LewdNeko** [comment]
One second, I'll open a PR to this branch on your fork.

**Comment by systemcrash** [comment]
I just re-based my master to match this master to align PRs here better.

**Comment by LewdNeko** [comment]
After the aforementioned issue is fixed this branch works as expected. Yet to test a "restart scenario" as I'm not quite sure how I can force one; open to suggestions.

**Comment by LewdNeko** [comment]
@systemcrash Excuse this being off-topc and the wrong place for this but is there anything setup for this repo that is better suited for lengthy and casual discussions about this repo and how it works?

**Comment by systemcrash** [comment]
Best is just to open an issue with a topic you want to discuss. If you
understand git and open source, you understand how this repo works 😎

**Pull request merged**
