### PR TITLE
use an interface IP instead of loopback

### PR DESCRIPTION
**Pull request by systemcrash**
Fixes startup problems and no longer mandates IPv6. 

See https://github.com/ckdo/airplay2-receiver/pull/16 for discussion

### CODE REVIEW

**Comment by Neustradamus** [comment]
@PaulWieland: What do you think?

**Comment by Neustradamus** [comment]
@systemcrash: Why have you closed it?

**Comment by Neustradamus** [comment]
@PaulWieland: Time to merge?

**Comment by Neustradamus** [comment]
@systemcrash: Can you add the new PR?

@PaulWieland: The other PR is good for you?

Thanks.

**Comment by Neustradamus** [comment]
@systemcrash: Any news about it?

**Comment by systemcrash** [comment]
You can pick it from a branch in my repo. https://github.com/systemcrash/airplay2-receiver/tree/set_interface_ip 
I have been using it by default. 

Nobody else seems interested in this repo...

**Comment by Neustradamus** [comment]
It is really used.
It is for this that you can do PRs and merge directly here...

**Review by glmnet — COMMENTED** [review]
Looks good

**Comment by LewdNeko** [comment]
Would love to see this, had to temporarily comment out all the IPV6-related

**Comment by systemcrash** [comment]
> It is for this that you can do PRs and merge directly here...

@Neustradamus I cannot merge by myself, if that's what you meant...

**Comment by LewdNeko** [comment]
> > It is for this that you can do PRs and merge directly here...
> 
> @Neustradamus I cannot merge by myself, if that's what you meant...

Is the maintainer of this repo active at all? If not, would it not be wise for someone with a lot of knowledge and input on this repo, let's say you, to create an indirect fork to which people can effectively contribute to and use?

There are many great contributions that seem to be almost left for dead.

**Comment by Neustradamus** [comment]
@systemcrash: And now? :)

All people are welcome to join the team!

**Comment by systemcrash** [comment]
I see it now 😄  Thank you.

**Comment by systemcrash** [comment]
We'll get it fixed.  Otherwise you can pick from my repo, although if you have some finished work, send PRs here. 

> Is the maintainer of this repo active at all? If not, would it not be wise for someone with a lot of knowledge and input on this repo, let's say you Paul, to create an indirect fork to which people can effectively contribute to and use?

**Pull request closed without merging**
